تحميل المكتبات

In [ ]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler

قراءة الملف

In [ ]:
df = pd.read_csv("cleaned_data.csv")

df

,Order,PID,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Lot Shape,Land Contour,Utilities,...,Enclosed Porch,3Ssn Porch,Screen Porch,Pool Area,Misc Val,Mo Sold,Yr Sold,Sale Type,Sale Condition,SalePrice
0,1,526301100,20,RL,141.0,31770,Pave,IR1,Lvl,AllPub,...,0,0,0,0,0,5,2010,WD,Normal,215000.0
1,2,526350040,20,RH,80.0,11622,Pave,Reg,Lvl,AllPub,...,0,0,120,0,0,6,2010,WD,Normal,105000.0
2,3,526351010,20,RL,81.0,14267,Pave,IR1,Lvl,AllPub,...,0,0,0,0,12500,6,2010,WD,Normal,172000.0
3,4,526353030,20,RL,93.0,11160,Pave,Reg,Lvl,AllPub,...,0,0,0,0,0,4,2010,WD,Normal,244000.0
4,5,527105010,60,RL,74.0,13830,Pave,IR1,Lvl,AllPub,...,0,0,0,0,0,3,2010,WD,Normal,189900.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2925,2926,923275080,80,RL,37.0,7937,Pave,IR1,Lvl,AllPub,...,0,0,0,0,0,3,2006,WD,Normal,142500.0
2926,2927,923276100,20,RL,68.0,8885,Pave,IR1,Low,AllPub,...,0,0,0,0,0,6,2006,WD,Normal,131000.0
2927,2928,923400125,85,RL,62.0,10441,Pave,Reg,Lvl,AllPub,...,0,0,0,0,700,7,2006,WD,Normal,132000.0
2928,2929,924100070,20,RL,77.0,10010,Pave,Reg,Lvl,AllPub,...,0,0,0,0,0,4,2006,WD,Normal,170000.0
2929,2930,924151050,60,RL,74.0,9627,Pave,Reg,Lvl,AllPub,...,0,0,0,0,0,11,2006,WD,Normal,188000.0

تحويل النصوص لأرقام

In [ ]:
df = pd.get_dummies(df, columns=["Neighborhood", "House Style"], drop_first=True)

df

,Order,PID,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Lot Shape,Land Contour,Utilities,...,Neighborhood_StoneBr,Neighborhood_Timber,Neighborhood_Veenker,House Style_1.5Unf,House Style_1Story,House Style_2.5Fin,House Style_2.5Unf,House Style_2Story,House Style_SFoyer,House Style_SLvl
0,1,526301100,20,RL,141.0,31770,Pave,IR1,Lvl,AllPub,...,False,False,False,False,True,False,False,False,False,False
1,2,526350040,20,RH,80.0,11622,Pave,Reg,Lvl,AllPub,...,False,False,False,False,True,False,False,False,False,False
2,3,526351010,20,RL,81.0,14267,Pave,IR1,Lvl,AllPub,...,False,False,False,False,True,False,False,False,False,False
3,4,526353030,20,RL,93.0,11160,Pave,Reg,Lvl,AllPub,...,False,False,False,False,True,False,False,False,False,False
4,5,527105010,60,RL,74.0,13830,Pave,IR1,Lvl,AllPub,...,False,False,False,False,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2925,2926,923275080,80,RL,37.0,7937,Pave,IR1,Lvl,AllPub,...,False,False,False,False,False,False,False,False,False,True
2926,2927,923276100,20,RL,68.0,8885,Pave,IR1,Low,AllPub,...,False,False,False,False,True,False,False,False,False,False
2927,2928,923400125,85,RL,62.0,10441,Pave,Reg,Lvl,AllPub,...,False,False,False,False,False,False,False,False,True,False
2928,2929,924100070,20,RL,77.0,10010,Pave,Reg,Lvl,AllPub,...,False,False,False,False,True,False,False,False,False,False
2929,2930,924151050,60,RL,74.0,9627,Pave,Reg,Lvl,AllPub,...,False,False,False,False,False,False,False,True,False,False

تغيير القيم

In [ ]:
qual_map = {
    "Po":1, "Fa":2, "TA":3, "Gd":4, "Ex":5
}

df["Exter Qual"] = df["Exter Qual"].map(qual_map)

df

,Order,PID,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Lot Shape,Land Contour,Utilities,...,Neighborhood_StoneBr,Neighborhood_Timber,Neighborhood_Veenker,House Style_1.5Unf,House Style_1Story,House Style_2.5Fin,House Style_2.5Unf,House Style_2Story,House Style_SFoyer,House Style_SLvl
0,1,526301100,20,RL,141.0,31770,Pave,IR1,Lvl,AllPub,...,False,False,False,False,True,False,False,False,False,False
1,2,526350040,20,RH,80.0,11622,Pave,Reg,Lvl,AllPub,...,False,False,False,False,True,False,False,False,False,False
2,3,526351010,20,RL,81.0,14267,Pave,IR1,Lvl,AllPub,...,False,False,False,False,True,False,False,False,False,False
3,4,526353030,20,RL,93.0,11160,Pave,Reg,Lvl,AllPub,...,False,False,False,False,True,False,False,False,False,False
4,5,527105010,60,RL,74.0,13830,Pave,IR1,Lvl,AllPub,...,False,False,False,False,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2925,2926,923275080,80,RL,37.0,7937,Pave,IR1,Lvl,AllPub,...,False,False,False,False,False,False,False,False,False,True
2926,2927,923276100,20,RL,68.0,8885,Pave,IR1,Low,AllPub,...,False,False,False,False,True,False,False,False,False,False
2927,2928,923400125,85,RL,62.0,10441,Pave,Reg,Lvl,AllPub,...,False,False,False,False,False,False,False,False,True,False
2928,2929,924100070,20,RL,77.0,10010,Pave,Reg,Lvl,AllPub,...,False,False,False,False,True,False,False,False,False,False
2929,2930,924151050,60,RL,74.0,9627,Pave,Reg,Lvl,AllPub,...,False,False,False,False,False,False,False,True,False,False

قسمة البيانات

In [ ]:
df["price_per_sqft"] = df["SalePrice"] / df["Gr Liv Area"]

df

,Order,PID,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Lot Shape,Land Contour,Utilities,...,Neighborhood_Timber,Neighborhood_Veenker,House Style_1.5Unf,House Style_1Story,House Style_2.5Fin,House Style_2.5Unf,House Style_2Story,House Style_SFoyer,House Style_SLvl,price_per_sqft
0,1,526301100,20,RL,141.0,31770,Pave,IR1,Lvl,AllPub,...,False,False,False,True,False,False,False,False,False,129.830918
1,2,526350040,20,RH,80.0,11622,Pave,Reg,Lvl,AllPub,...,False,False,False,True,False,False,False,False,False,117.187500
2,3,526351010,20,RL,81.0,14267,Pave,IR1,Lvl,AllPub,...,False,False,False,True,False,False,False,False,False,129.420617
3,4,526353030,20,RL,93.0,11160,Pave,Reg,Lvl,AllPub,...,False,False,False,True,False,False,False,False,False,115.639810
4,5,527105010,60,RL,74.0,13830,Pave,IR1,Lvl,AllPub,...,False,False,False,False,False,False,True,False,False,116.574586
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2925,2926,923275080,80,RL,37.0,7937,Pave,IR1,Lvl,AllPub,...,False,False,False,False,False,False,False,False,True,142.073779
2926,2927,923276100,20,RL,68.0,8885,Pave,IR1,Low,AllPub,...,False,False,False,True,False,False,False,False,False,145.232816
2927,2928,923400125,85,RL,62.0,10441,Pave,Reg,Lvl,AllPub,...,False,False,False,False,False,False,False,True,False,136.082474
2928,2929,924100070,20,RL,77.0,10010,Pave,Reg,Lvl,AllPub,...,False,False,False,True,False,False,False,False,False,122.390209
2929,2930,924151050,60,RL,74.0,9627,Pave,Reg,Lvl,AllPub,...,False,False,False,False,False,False,True,False,False,94.000000

ضرب البيانات

In [ ]:
df["quality_area"] = df["Overall Qual"] * df["Gr Liv Area"]

df

,Order,PID,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Lot Shape,Land Contour,Utilities,...,Neighborhood_Veenker,House Style_1.5Unf,House Style_1Story,House Style_2.5Fin,House Style_2.5Unf,House Style_2Story,House Style_SFoyer,House Style_SLvl,price_per_sqft,quality_area
0,1,526301100,20,RL,141.0,31770,Pave,IR1,Lvl,AllPub,...,False,False,True,False,False,False,False,False,129.830918,9936
1,2,526350040,20,RH,80.0,11622,Pave,Reg,Lvl,AllPub,...,False,False,True,False,False,False,False,False,117.187500,4480
2,3,526351010,20,RL,81.0,14267,Pave,IR1,Lvl,AllPub,...,False,False,True,False,False,False,False,False,129.420617,7974
3,4,526353030,20,RL,93.0,11160,Pave,Reg,Lvl,AllPub,...,False,False,True,False,False,False,False,False,115.639810,14770
4,5,527105010,60,RL,74.0,13830,Pave,IR1,Lvl,AllPub,...,False,False,False,False,False,True,False,False,116.574586,8145
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2925,2926,923275080,80,RL,37.0,7937,Pave,IR1,Lvl,AllPub,...,False,False,False,False,False,False,False,True,142.073779,6018
2926,2927,923276100,20,RL,68.0,8885,Pave,IR1,Low,AllPub,...,False,False,True,False,False,False,False,False,145.232816,4510
2927,2928,923400125,85,RL,62.0,10441,Pave,Reg,Lvl,AllPub,...,False,False,False,False,False,False,True,False,136.082474,4850
2928,2929,924100070,20,RL,77.0,10010,Pave,Reg,Lvl,AllPub,...,False,False,True,False,False,False,False,False,122.390209,6945
2929,2930,924151050,60,RL,74.0,9627,Pave,Reg,Lvl,AllPub,...,False,False,False,False,False,True,False,False,94.000000,14000

موازنة البيانات

In [ ]:
df["SalePrice_log"] = np.log1p(df["SalePrice"])

df

,Order,PID,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Lot Shape,Land Contour,Utilities,...,House Style_1.5Unf,House Style_1Story,House Style_2.5Fin,House Style_2.5Unf,House Style_2Story,House Style_SFoyer,House Style_SLvl,price_per_sqft,quality_area,SalePrice_log
0,1,526301100,20,RL,141.0,31770,Pave,IR1,Lvl,AllPub,...,False,True,False,False,False,False,False,129.830918,9936,12.278398
1,2,526350040,20,RH,80.0,11622,Pave,Reg,Lvl,AllPub,...,False,True,False,False,False,False,False,117.187500,4480,11.561725
2,3,526351010,20,RL,81.0,14267,Pave,IR1,Lvl,AllPub,...,False,True,False,False,False,False,False,129.420617,7974,12.055256
3,4,526353030,20,RL,93.0,11160,Pave,Reg,Lvl,AllPub,...,False,True,False,False,False,False,False,115.639810,14770,12.404928
4,5,527105010,60,RL,74.0,13830,Pave,IR1,Lvl,AllPub,...,False,False,False,False,True,False,False,116.574586,8145,12.154258
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2925,2926,923275080,80,RL,37.0,7937,Pave,IR1,Lvl,AllPub,...,False,False,False,False,False,False,True,142.073779,6018,11.867104
2926,2927,923276100,20,RL,68.0,8885,Pave,IR1,Low,AllPub,...,False,True,False,False,False,False,False,145.232816,4510,11.782960
2927,2928,923400125,85,RL,62.0,10441,Pave,Reg,Lvl,AllPub,...,False,False,False,False,False,True,False,136.082474,4850,11.790565
2928,2929,924100070,20,RL,77.0,10010,Pave,Reg,Lvl,AllPub,...,False,True,False,False,False,False,False,122.390209,6945,12.043560
2929,2930,924151050,60,RL,74.0,9627,Pave,Reg,Lvl,AllPub,...,False,False,False,False,True,False,False,94.000000,14000,12.144203

توحيد القيم

In [ ]:
scaler = StandardScaler()

df[["Gr Liv Area", "Total Bsmt SF"]] = scaler.fit_transform(
    df[["Gr Liv Area", "Total Bsmt SF"]]
)

df

,Order,PID,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Lot Shape,Land Contour,Utilities,...,House Style_1.5Unf,House Style_1Story,House Style_2.5Fin,House Style_2.5Unf,House Style_2Story,House Style_SFoyer,House Style_SLvl,price_per_sqft,quality_area,SalePrice_log
0,1,526301100,20,RL,141.0,31770,Pave,IR1,Lvl,AllPub,...,False,True,False,False,False,False,False,129.830918,9936,12.278398
1,2,526350040,20,RH,80.0,11622,Pave,Reg,Lvl,AllPub,...,False,True,False,False,False,False,False,117.187500,4480,11.561725
2,3,526351010,20,RL,81.0,14267,Pave,IR1,Lvl,AllPub,...,False,True,False,False,False,False,False,129.420617,7974,12.055256
3,4,526353030,20,RL,93.0,11160,Pave,Reg,Lvl,AllPub,...,False,True,False,False,False,False,False,115.639810,14770,12.404928
4,5,527105010,60,RL,74.0,13830,Pave,IR1,Lvl,AllPub,...,False,False,False,False,True,False,False,116.574586,8145,12.154258
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2925,2926,923275080,80,RL,37.0,7937,Pave,IR1,Lvl,AllPub,...,False,False,False,False,False,False,True,142.073779,6018,11.867104
2926,2927,923276100,20,RL,68.0,8885,Pave,IR1,Low,AllPub,...,False,True,False,False,False,False,False,145.232816,4510,11.782960
2927,2928,923400125,85,RL,62.0,10441,Pave,Reg,Lvl,AllPub,...,False,False,False,False,False,True,False,136.082474,4850,11.790565
2928,2929,924100070,20,RL,77.0,10010,Pave,Reg,Lvl,AllPub,...,False,True,False,False,False,False,False,122.390209,6945,12.043560
2929,2930,924151050,60,RL,74.0,9627,Pave,Reg,Lvl,AllPub,...,False,False,False,False,True,False,False,94.000000,14000,12.144203

طرح البيانات و تقسيمها الى فئات

In [ ]:
df["age"] = df["Yr Sold"] - df["Year Built"]

df["age_group"] = pd.cut(
    df["age"],
    bins=[0, 10, 30, 100],
    labels=["New", "Recent", "Old"]
)

df

,Order,PID,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Lot Shape,Land Contour,Utilities,...,House Style_2.5Fin,House Style_2.5Unf,House Style_2Story,House Style_SFoyer,House Style_SLvl,price_per_sqft,quality_area,SalePrice_log,age,age_group
0,1,526301100,20,RL,141.0,31770,Pave,IR1,Lvl,AllPub,...,False,False,False,False,False,129.830918,9936,12.278398,50,Old
1,2,526350040,20,RH,80.0,11622,Pave,Reg,Lvl,AllPub,...,False,False,False,False,False,117.187500,4480,11.561725,49,Old
2,3,526351010,20,RL,81.0,14267,Pave,IR1,Lvl,AllPub,...,False,False,False,False,False,129.420617,7974,12.055256,52,Old
3,4,526353030,20,RL,93.0,11160,Pave,Reg,Lvl,AllPub,...,False,False,False,False,False,115.639810,14770,12.404928,42,Old
4,5,527105010,60,RL,74.0,13830,Pave,IR1,Lvl,AllPub,...,False,False,True,False,False,116.574586,8145,12.154258,13,Recent
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2925,2926,923275080,80,RL,37.0,7937,Pave,IR1,Lvl,AllPub,...,False,False,False,False,True,142.073779,6018,11.867104,22,Recent
2926,2927,923276100,20,RL,68.0,8885,Pave,IR1,Low,AllPub,...,False,False,False,False,False,145.232816,4510,11.782960,23,Recent
2927,2928,923400125,85,RL,62.0,10441,Pave,Reg,Lvl,AllPub,...,False,False,False,True,False,136.082474,4850,11.790565,14,Recent
2928,2929,924100070,20,RL,77.0,10010,Pave,Reg,Lvl,AllPub,...,False,False,False,False,False,122.390209,6945,12.043560,32,Old
2929,2930,924151050,60,RL,74.0,9627,Pave,Reg,Lvl,AllPub,...,False,False,True,False,False,94.000000,14000,12.144203,13,Recent

اقوى الاعمدة تأثير

In [ ]:
corr = df.corr(numeric_only=True)

high_corr = corr["SalePrice"].abs().sort_values(ascending=False)

df

,Order,PID,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Lot Shape,Land Contour,Utilities,...,House Style_2.5Fin,House Style_2.5Unf,House Style_2Story,House Style_SFoyer,House Style_SLvl,price_per_sqft,quality_area,SalePrice_log,age,age_group
0,1,526301100,20,RL,141.0,31770,Pave,IR1,Lvl,AllPub,...,False,False,False,False,False,129.830918,9936,12.278398,50,Old
1,2,526350040,20,RH,80.0,11622,Pave,Reg,Lvl,AllPub,...,False,False,False,False,False,117.187500,4480,11.561725,49,Old
2,3,526351010,20,RL,81.0,14267,Pave,IR1,Lvl,AllPub,...,False,False,False,False,False,129.420617,7974,12.055256,52,Old
3,4,526353030,20,RL,93.0,11160,Pave,Reg,Lvl,AllPub,...,False,False,False,False,False,115.639810,14770,12.404928,42,Old
4,5,527105010,60,RL,74.0,13830,Pave,IR1,Lvl,AllPub,...,False,False,True,False,False,116.574586,8145,12.154258,13,Recent
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2925,2926,923275080,80,RL,37.0,7937,Pave,IR1,Lvl,AllPub,...,False,False,False,False,True,142.073779,6018,11.867104,22,Recent
2926,2927,923276100,20,RL,68.0,8885,Pave,IR1,Low,AllPub,...,False,False,False,False,False,145.232816,4510,11.782960,23,Recent
2927,2928,923400125,85,RL,62.0,10441,Pave,Reg,Lvl,AllPub,...,False,False,False,True,False,136.082474,4850,11.790565,14,Recent
2928,2929,924100070,20,RL,77.0,10010,Pave,Reg,Lvl,AllPub,...,False,False,False,False,False,122.390209,6945,12.043560,32,Old
2929,2930,924151050,60,RL,74.0,9627,Pave,Reg,Lvl,AllPub,...,False,False,True,False,False,94.000000,14000,12.144203,13,Recent

حفظ البيانات في ملف csv

In [ ]:
df.to_csv("featured_data.csv", index=False)

df

,Order,PID,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Lot Shape,Land Contour,Utilities,...,House Style_2.5Fin,House Style_2.5Unf,House Style_2Story,House Style_SFoyer,House Style_SLvl,price_per_sqft,quality_area,SalePrice_log,age,age_group
0,1,526301100,20,RL,141.0,31770,Pave,IR1,Lvl,AllPub,...,False,False,False,False,False,129.830918,9936,12.278398,50,Old
1,2,526350040,20,RH,80.0,11622,Pave,Reg,Lvl,AllPub,...,False,False,False,False,False,117.187500,4480,11.561725,49,Old
2,3,526351010,20,RL,81.0,14267,Pave,IR1,Lvl,AllPub,...,False,False,False,False,False,129.420617,7974,12.055256,52,Old
3,4,526353030,20,RL,93.0,11160,Pave,Reg,Lvl,AllPub,...,False,False,False,False,False,115.639810,14770,12.404928,42,Old
4,5,527105010,60,RL,74.0,13830,Pave,IR1,Lvl,AllPub,...,False,False,True,False,False,116.574586,8145,12.154258,13,Recent
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2925,2926,923275080,80,RL,37.0,7937,Pave,IR1,Lvl,AllPub,...,False,False,False,False,True,142.073779,6018,11.867104,22,Recent
2926,2927,923276100,20,RL,68.0,8885,Pave,IR1,Low,AllPub,...,False,False,False,False,False,145.232816,4510,11.782960,23,Recent
2927,2928,923400125,85,RL,62.0,10441,Pave,Reg,Lvl,AllPub,...,False,False,False,True,False,136.082474,4850,11.790565,14,Recent
2928,2929,924100070,20,RL,77.0,10010,Pave,Reg,Lvl,AllPub,...,False,False,False,False,False,122.390209,6945,12.043560,32,Old
2929,2930,924151050,60,RL,74.0,9627,Pave,Reg,Lvl,AllPub,...,False,False,True,False,False,94.000000,14000,12.144203,13,Recent